name: resep_nusantara
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  http: ^1.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/traditional_food_background.jpg
    - assets/images/food/nasi_goreng.jpg
    - assets/images/food/rendang.jpg
    - assets/images/food/soto_betawi.jpg
    - assets/images/food/sate_ayam.jpg
    - assets/images/food/ketoprak.jpg
    - assets/images/food/bakso.jpeg
    - assets/images/drink/kopi_tubruk.jpg
    - assets/images/drink/kopi_luwak.jpg
    - assets/images/drink/wedang_jahe.jpg
    - assets/images/drink/soda_gembira.jpg
    - assets/images/drink/teh_talua.jpg
    - assets/images/drink/sekoteng.jpg

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
